server:
  port: 8002
spring:
  application:
    name: coder-auth
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  redis:
    database: 0
    host: xxx
    port: 6379
    password: xx
    timeout: 5000
    jedis:
      pool:
        max-active: 1024  # 最大连接数（使用负值表示没有限制）
        max-wait: -1      # 最大连接阻塞等待时间，单位毫秒，默认-1（使用负值表示没有限制）
        max-idle: 200       # 最大空闲连接，默认8
        min-idle: 0       # 最小空闲连接，默认0
        time-between-eviction-runs: 30000   # 逐出运行之间的时间(毫秒)

  cloud:
    nacos:
      discovery:
        server-addr: xxx
        username: xx
        password: xx
        ip: xx
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xx:3306/code_auth?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: xx
    password: xx
    # 连接池配置
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM sys_user
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开 PSCache，并且指定每个连接上 PSCache 的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的 Filter，去掉后监控界面 SQL 无法统计，wall 用于防火墙
      filters: stat,wall
      # 通过 connection-properties 属性打开 mergeSql 功能；慢 SQL 记录
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置 DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
      # 配置 DruidStatViewServlet
      stat-view-servlet:
        url-pattern: /druid/*
        # IP 白名单，没有配置或者为空，则允许所有访问
        allow: 127.0.0.1
        # 禁用 HTML 中 Reset All 按钮
        reset-enable: false
        # 登录用户名/密码
        login-username: root
        login-password: 123456
# Feign 配置
feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
